- requirements.txt
python-dateutil is needed by decor.py, adding it to requirements.txt.
Signed-off-by: Jason Joyce <jjoyce@redhat.com>
> Adding python-dateutil to requirements.txt

- contrib/trolly.json
- trolly/decor.py
- trolly/jira_cli.py
**Jira: add proxy support**
Some Jira instances may require using a proxy. Enable defining them in
the trolly config and default to no proxy when the entry is missing.
**Use get_terminal_size from shutil instead of os**
os's get_terminal_size breaks when not calling from a real console,
such as when using an IDE's run configurations.
Also, Python docs[1] say to preferably use shutil.
[1] https://docs.python.org/3/library/os.html#os.get_terminal_size
> Add proxy support, small terminal fixup

- README.md
Reason: when reading the README.md file, someone may get confused about this '.' char, not noticing it means the current dir and not just an ordinary period to finish a sentence
> Add two lines for pip install

- jirate/jboard.py
- jirate/tests/__init__.py
- jirate/tests/test_jirate.py
The way the jira module for python is implemented, there's no simple way to feed the server's custom
field definitions to produce something human-readable that can be used in code, i.e.:
issue.fields.fixed_in_build
vs.
issue.fields.custom_321789045789
or:
issue.raw['fields']['fixed_in_build']
vs.
issue.raw['fields']['custom_321789045789']
The raw JSON returned from the JIRA server for an issue does not contain any of the mapping information, which must be retrieved separately. Fortunately, this changes infrequently, so we can cache it in the Jirate() object for now, although if we want this to work for long-running processes, it should be updated periodically.
So, we're left with:
jirate.field(issue, 'fixed_in_build')
or
issue.field('fixed_in_build')
... which lazy-loads the field …
> jira: Add a custom field mapping resolver

- jirate/jboard.py
- jirate/jira_input.py
- jirate/tests/__init__.py
- jirate/tests/test_input.py
- jirate/tests/test_render.py
Previous round of commits:
- didn't factor in that metadata was now always required when calling create(), and
-  left code in when doing subtask creation that was needed before we expanded transmogrify_input().
This fixes those related issues and adds tests for issuelink values, which was missing.
> jira: Fix up parent linking

- jirate/jira_cli.py
When we expanded vsep_print() we missed a line in cat -v
> jira: Fix CLI bug with cat -v

- jirate/jboard.py
Passing `query=xxx` results in a 400
> jira: Fix get_user()

- PKG-INFO
- contrib/example-template.yaml
- jirate/__init__.py
- jirate/jboard.py
- jirate/jira_cli.py
- jirate/jira_input.py
- jirate/schemas/issue.yaml
- jirate/schemas/subtask.yaml
- jirate/tests/__init__.py
- jirate/tests/templates/bad-template.yaml
- jirate/tests/templates/good-template.yaml
- jirate/tests/test_jira_cli.py
With this change, you can use any custom field you could use from the CLI within templates using the `nym` or field name. Ex: `story_points`, or `fixversions`
> Use create() instead of new() when processing templates

- PKG-INFO
- jirate/__init__.py
- jirate/jira_input.py
- jirate/tests/__init__.py
- jirate/tests/test_jira_cli.py
Subtask creation requires 'parent': {'key': 'TEST-1'} format.
Creation metadata says issuelink is the type. We were skipping this in create() and tests were incorect as a result.
> jira: Fix bug in subtask code

- jirate/jboard.py
- jirate/jira_cli.py
- jirate/tests/test_jirate.py
The existing field_map() function was able to translate human-readable names into field IDs. Renamed that to field_to_id() and added similar functions to similarly translate to full names and to aliases as well.
This will make it easier to work with fields when we read user input or write output that humans as supposed to parse easily.
> Add field translation functions

- jirate/jboard.py
- jirate/jira_cli.py
Since we have issue.field() resolver, now we have the issue.update_field(...) call so users don't have have to think about updating things. We now call this from the CLI as well.
> Attach high level update_field() to Issue resources

- jirate/jira_input.py
- jirate/tests/__init__.py
- jirate/tests/test_input.py
This makes fuzzy value usage more precise. Previously, if >1 match happened when something matched exactly, we would fail with ValueError. This PR:
- Makes exact matches preempt fuzzy matches
- Ensures output list order matches input list order
- Improves tests around all of this
> Fuzzy values fix

- jirate/jira_cli.py
When truncating fields, we were preserving the full width of the field name but truncating the field values.  For example, one could end up like so if using "issuetype:5,summary" as the fields option:
key    | issuetype | summary
TEST-1 | Feat…     | whatever
This makes it:
key    | issu… | summary
TEST-1 | Feat… | whatever
> jira: Truncate field headers

- contrib/example-template.yaml
- jirate/jira_cli.py
- jirate/template_vars.py
- jirate/tests/test_template_vars.py
- requirements.txt
- Use two common jinja2 "default" variable templates
- Allow interactive input when desired
- Require all variables detected in a template to be provided
- Variables can be provided on the command line (just like jirate create name value name2 value2) 
- For variables provided on the command line, do not prompt user
- Variables that are not in the template raise errors
- I may have been hungry when writing the last test.
> Jinja2 template variables

- jirate/jira_cli.py
Sometimes, you have hundreds of issues to go through but want to prune that list a bit.  For example:
$ jirate search -n mysearch 'summary ~ pork'
This change prepends the named search with additional text, allowing flexibility, like so:
(additional seach things) AND [mysearch]
> jira: Allow combining a named search with raw cli

- contrib/jirate.json
- jirate/decor.py
- jirate/jira_cli.py
Gnome-terminal and a few others support complicated terminal artifacts such as hyperlinks. When fancy output is turned on, this will render hyperlinks for issues, allowing the user to right-click and "open hyperlink".
> Add fancy output

- jirate/jira_cli.py
- jirate/jira_input.py
The Jira REST APIs for sprints are an entirely different API tree (/rest/sprint/1.0 vs /rest/api/latest/...).
Until a major feature is added to support the new API tree and using it properly, this can be used as a quick and dirty way to add an issue to a sprint, i.e.:
$ jirate field MYKEY-123 set sprint 12345
Unfortunately, there's no way to set via "name".
> (dirty) Allow sprint setting by ID

- jirate/jira_cli.py
The summary and description fields were being pruned for no particular reason from `jirate field set` operations; I think I made the decision to force people to use `jirate edit` (but don't recall the logic if there was any).
So, allow editing those.
Then, add a patch to allow simple substitution of values therein. Technically, one could do this on any string. I caution users to not try this on list fields. I haven't tried it.
`jirate field sub summary 'old_text' 'new_text'`
> Field substitution

- jirate/jira_cli.py
When generating a template from an issue, if a line in the description of the issue or a subtask had a trailing space, python yaml would encode the whole thing as a quoted string instead of a block-quote like it should have been.
By iterating through the text and stripping off trailing whitespace, first on the whole, then on each line individually, this issue is resolved.
Related to: https://github.com/yaml/pyyaml/issues/121
Found / original patch by Jon Schlueter @yazug
> Fix block quote handling

- contrib/jirate.json
- jirate/decor.py
- jirate/jboard.py
- jirate/jira_cli.py
Features:
- Read sprint information for project (beta? alpha?)
- Compact output - remove columns where no issues have a value set (previously, we automatically removed a column if the field wasn't valid for all issues in the list)
Fixes:
- Flake8 errors
- Don't print issue lengths when we printed nothing because the screen was too narrow
- Don't print "None" when there's no value; leave it blank. (The text "None" could be a valid value)
> Development Branch

- jirate/jira_custom.py
- jirate/jira_fields.py
- jirate/tests/test_jira_custom.py
- Render sprints by parsing the data
- Disable rendering of several field categories for now. Note that users' configuration overrides for how to display these fields, if present, are preserved.
> jira: Add internal rendering for some custom fields

- jirate/jboard.py
- jirate/jira_cli.py
Also resolves using fixversions in fields output.
fixversions and lastviewed are internal JIRA fields which have camel case naming, so we need to alias them or else searching by field or displaying by field would require ensuring we type in the Jira field value instead of an alias since they are not returned in /field
> Fix fixversions search

- README.md
- jirate/decor.py
- jirate/jboard.py
- jirate/jira_cli.py
- jirate/jira_fields.py
- jirate/rqcache.py
- Give visual separation between lines in drawn matrices when `fancy_output` is turned on, but let users configure it if they do not like it
- Display attachment information in verbose mode when viewing issues
- When a field or operation expects a user, try really hard to resolve the username for the user.
- Don't assume users with @ is an email address - it's possible to have an email address and a username that looks like an email address but have them be different.
- Be better about printing exceptions when things fail
- Don't always join content when updating fields - some field updates expect arrays
- When listing lots of subtasks and their parents, indicate visually if a parent task is closed while a subtask is not
> Started as a minimal update, but now has maximal updates.

- README.md
- jirate/decor.py
- jirate/jira_cli.py
- jirate/jira_fields.py
- Allow CSV output of individual issues with a constrained set of fields
- Allow configuring default fields when using `cat`, specifically
- Show sprint start and end dates
> More comprehensive field configuration

- pyproject.toml
Set a minimum python version (3.9) that has to be used. Also added two dependency groups (dev and lint) to the pyproject file. This allows us to further migrate away from the older requirements.txt files.
> Updating some of the packaging.

- jirate/jira_cli.py
(If there is exactly one)
This could be controversial, but having to remember a sprint ID in all cases is not user-focused.  This changes the behavior of sprint_info() to list the issues in the sole active sprint, if querying the sprint table nets one active sprint. Else, it prints the sprint list like before.
A new flag (-l, --list) is added to always list current and future sprints.
This relies on caching to reduce RTs to the Jira server
> CLI BREAK: automatically print the active sprint
